spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # useSSL=false&allowPublicKeyRetrieval=true is required from 8.x.x for security issue
    url: jdbc:mysql://${DB_ADDRESS}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
  session:
    store-type: redis
    timeout: ${SESSION_TIMEOUT}

redis:
  session:
    master:
      node: ${REDIS_SESSION_MASTER_NODE}
    password: ${REDIS_NODE_PASSWORD}

logging:
  level:
    root: info

cloud:
  credentials:
    access-key: ${CLOUD_ACCESS_KEY}
    secret-key: ${CLOUD_SECRET_KEY}
  storage:
    endpoint: ${STORAGE_END_POINT}
    region:
      static: ${STORAGE_REGION}
    bucket-name: ${STORAGE_BUCKET_NAME}
